### ISSUE TITLE
No dark theme option / icons

### ISSUE THREAD

**Issue by MirceaMx** [freywazza/Yosa-Max-Git#1]
Some icons look terrible with a dark theme (using Breeze Dark)...had to switch to another icon theme. It looks great but some icons are barely visible (dark icons on dark theme).

**Comment by freywazza** [comment]
Yeah, I'm actually aware of this since the beginning, cause I'm not a big fan of any dark theme. I'll consider to add a dark variant to this icon theme later, but it probably won't come soon.

**Comment by demoy** [comment]
@freywazza 
@MirceaMx 

You can quickly (little over a minute) make turn this theme dark by using sed and find
![Screenshot_20190408_174030](https://user-images.githubusercontent.com/2396524/55761589-708ba300-5a25-11e9-8819-7f0956eff252.png)

find . -exec sed -i -e 's/4d4d4d/dbe7ff/g' {} \;
find . -exec sed -i -e 's/303030/dbe7ff/g' {} \;

This command will replace the colors 4d4d4d and 303030 with dbe7ff (replace dbe7ff with your prefer 'light' color) "cd" to the Yosa directory in your terminal before running the 2 lines (make a backup of Yosa it modifies the theme) .

//4d4d4d is the color of the toolbar icons in Yosa
//303030 is the color of small places icons in Yosa

You don't have to make them the same color in the light version: the KDE default themes uses 1 color for monochrome, so I went with 1 as well.

You can read about sed here (http://www.grymoire.com/Unix/Sed.html)

![Screenshot_20190408_175858](https://user-images.githubusercontent.com/2396524/55762485-b85ff980-5a28-11e9-97f4-8ec792f9c48f.png)

![Screenshot_20190408_180017](https://user-images.githubusercontent.com/2396524/55762486-b8f89000-5a28-11e9-9d3a-5a9ee8c77905.png)

Most of the major icon themes just recolor the monochrome icons to make a "dark icon" version, so this method gets the job done completely. You can also be slightly more fancy like Papirus, and recolor the folders in the dark theme (Pink please :). But even then this gets you most of the way.

**Comment by freywazza** [comment]
Thanks demoy, I'm aware of using the sed script to change the svg color, I use it quite frequently to change the svg colors in batch. I'll consider to add a dark variant to this icon theme.

**Comment by freywazza** [comment]
A dark variant has been added.

**Comment by demoy** [comment]
Thank you
