### ISSUE TITLE
Icon request: OpenRA mods

### ISSUE THREAD

**Issue by fusion809** [freywazza/Yosa-Max-Git#2]
Hi,

I love this theme, it is truly underrated, but I would like to request icons for the official Dune 2K, Red Alert and Tiberian Dawn mods of the [OpenRA](https://github.com/OpenRA/OpenRA) game. Tiberian Dawn's logo is:

![cnc_128x128](https://user-images.githubusercontent.com/4717341/50315758-b7e63600-04ff-11e9-9668-80e9c271e2bf.png)

its icon name is openra-cnc. Dune 2K's is:

![d2k_128x128](https://user-images.githubusercontent.com/4717341/50315771-c9c7d900-04ff-11e9-9cb0-604106e07444.png)

and is named openra-d2k. Red Alert's is:

![ra_128x128](https://user-images.githubusercontent.com/4717341/50315801-dd733f80-04ff-11e9-8544-59351c6d433a.png)

and is named openra-ra. 

Thanks for your time,
Brenton

**Comment by freywazza** [comment]
hi there, sorry for such a really late reply, but I'll remember to include it in the next update, thanks.

**Comment by freywazza** [comment]
New icons added.
