### ISSUE TITLE
Add symbolic link "audio-flac.svg"

### ISSUE THREAD

**Issue by demoy** [freywazza/Yosa-Max-Git#3]
(A bit of fanboying first).. these are the best mimetypes I have ever seen. Consistent yet distinguishable, pretty yet not distracting (to me atleast).

(the issue).. add a symbolic in (mimetypes/scalable) of (application-audio.svg) name the link (audio-flac.svg). If you don't KDE defaults to using the Breeze icon theme for the flac mimetypes.

I resolved this issue on my locale copy so close this issue here when you resolve it on your branch.

**Comment by freywazza** [comment]
Thanks demoy, so glad to know that you love it :).
I'll fix it as soon as I get access to my pc.

**Comment by freywazza** [comment]
Fixed, thank you.
