### ISSUE TITLE
.ttf and .cbz  mime extension support request

### ISSUE THREAD

**Issue by demoy** [freywazza/Yosa-Max-Git#6]
.ttf mime extension is absent interestingly .otf is present. Perhaps add a symbolic link for this one: 
![Screenshot_20191006_093916](https://user-images.githubusercontent.com/2396524/66270848-913e8500-e81d-11e9-82cb-f5dab9466914.png)

having the .cbz extension would be a niceity: 
![Screenshot_20191006_094227](https://user-images.githubusercontent.com/2396524/66270880-e4183c80-e81d-11e9-811d-8b25c4a582de.png)

**Comment by freywazza** [comment]
Got it, I'll add it soon

**Comment by freywazza** [comment]
added.

**Comment by demoy** [comment]
thanks
